'use client';

import { useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { motion, AnimatePresence } from 'framer-motion';
import {
  ArrowRight, Brain, Check, Eye, EyeOff, Github, Loader2,
  Lock, Mail, Mic, Shield, Sparkles, User, X, Zap,
} from 'lucide-react';
import { useGoogleLogin } from '@react-oauth/google';
import { api } from '@/services/api';

/* ── helpers ── */
const passRules = [
  { label: 'At least 8 characters', test: (p: string) => p.length >= 8 },
  { label: 'Uppercase letter', test: (p: string) => /[A-Z]/.test(p) },
  { label: 'Lowercase letter', test: (p: string) => /[a-z]/.test(p) },
  { label: 'Number', test: (p: string) => /\d/.test(p) },
  { label: 'Special character', test: (p: string) => /[^A-Za-z0-9]/.test(p) },
];

function passStrength(p: string) {
  const score = passRules.filter(r => r.test(p)).length;
  if (score <= 1) return { label: 'Very Weak', color: '#f43f5e', pct: 20 };
  if (score === 2) return { label: 'Weak', color: '#f59e0b', pct: 40 };
  if (score === 3) return { label: 'Fair', color: '#eab308', pct: 60 };
  if (score === 4) return { label: 'Strong', color: '#10b981', pct: 80 };
  return { label: 'Very Strong', color: '#00e5ff', pct: 100 };
}

/* ── modal ── */
function PolicyModal({ title, onClose }: { title: string; onClose: () => void }) {
  return (
    <AnimatePresence>
      <motion.div
        className="fixed inset-0 z-50 flex items-center justify-center p-4"
        initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
      >
        <div className="absolute inset-0 bg-black/70 backdrop-blur-sm" onClick={onClose} />
        <motion.div
          className="relative z-10 w-full max-w-lg rounded-2xl p-8"
          style={{ background: 'var(--bg-surface)', border: '1px solid var(--border)' }}
          initial={{ scale: 0.9, opacity: 0 }} animate={{ scale: 1, opacity: 1 }}
        >
          <div className="flex items-center justify-between mb-6">
            <div className="flex items-center gap-2">
              <Shield className="h-5 w-5" style={{ color: 'var(--accent-cyan)' }} />
              <h2 className="text-xl font-bold" style={{ color: 'var(--ink)' }}>{title}</h2>
            </div>
            <button onClick={onClose} className="rounded-lg p-1.5 hover:bg-white/10 transition">
              <X className="h-5 w-5" style={{ color: 'var(--ink-secondary)' }} />
            </button>
          </div>
          <div className="space-y-4 text-sm" style={{ color: 'var(--ink-secondary)', maxHeight: '60vh', overflowY: 'auto' }}>
            {title === 'Terms & Conditions' ? (
              <>
                <p><strong style={{ color: 'var(--ink)' }}>1. Acceptance of Terms</strong><br />By accessing AI Communication Coach, you agree to these Terms & Conditions. If you disagree, do not use the service.</p>
                <p><strong style={{ color: 'var(--ink)' }}>2. Use of Service</strong><br />You may use this platform for personal communication skill development. Misuse, scraping, or commercial redistribution is prohibited without written consent.</p>
                <p><strong style={{ color: 'var(--ink)' }}>3. AI-Generated Content</strong><br />Feedback and scores are generated by AI models. They are advisory and should not be treated as professional assessments.</p>
                <p><strong style={{ color: 'var(--ink)' }}>4. Account Responsibility</strong><br />You are responsible for maintaining the confidentiality of your account credentials. Notify us immediately of any unauthorized use.</p>
                <p><strong style={{ color: 'var(--ink)' }}>5. Termination</strong><br />We reserve the right to suspend or terminate accounts that violate these terms at our sole discretion.</p>
                <p><strong style={{ color: 'var(--ink)' }}>6. Changes to Terms</strong><br />We may update these terms periodically. Continued use of the platform constitutes acceptance of revised terms.</p>
              </>
            ) : (
              <>
                <p><strong style={{ color: 'var(--ink)' }}>1. Data We Collect</strong><br />We collect your email, name, audio transcripts during sessions, and usage analytics to improve our service.</p>
                <p><strong style={{ color: 'var(--ink)' }}>2. How We Use Your Data</strong><br />Your data is used exclusively to power AI coaching features, track progress, and improve platform performance. We do not sell your data.</p>
                <p><strong style={{ color: 'var(--ink)' }}>3. Data Storage</strong><br />Data is stored securely using industry-standard encryption. Session recordings are not stored — only text transcripts used for scoring.</p>
                <p><strong style={{ color: 'var(--ink)' }}>4. Third-Party Services</strong><br />We use Google OAuth for authentication. Google's privacy policy applies to that portion of data handling.</p>
                <p><strong style={{ color: 'var(--ink)' }}>5. Your Rights</strong><br />You may request deletion of your account and associated data at any time by contacting our support team.</p>
                <p><strong style={{ color: 'var(--ink)' }}>6. Cookies</strong><br />We use session cookies for authentication purposes only. No third-party tracking cookies are used.</p>
              </>
            )}
          </div>
          <button onClick={onClose} className="btn-primary mt-6 w-full">Got it</button>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}

/* ── main ── */
export default function AuthPage() {
  const router = useRouter();
  const [mode, setMode] = useState<'login' | 'signup' | 'forgot'>('login');
  const [email, setEmail] = useState('');
  const [fullName, setFullName] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPass, setConfirmPass] = useState('');
  const [showPass, setShowPass] = useState(false);
  const [showConfirm, setShowConfirm] = useState(false);
  const [rememberMe, setRememberMe] = useState(false);
  const [termsAccepted, setTermsAccepted] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [slowHint, setSlowHint] = useState(false);
  const [modal, setModal] = useState<'terms' | 'privacy' | null>(null);
  const slowRef = useRef<NodeJS.Timeout | null>(null);

  useEffect(() => {
    const handleMessage = (event: MessageEvent) => {
      if (event.origin !== window.location.origin && event.origin !== 'http://localhost:8000') {
        // In dev, the API might be on 8000
        if (!event.origin.includes('localhost') && !event.origin.includes('render.com')) return;
      }

        if (event.data?.type === 'oauth-token' && event.data?.token) {
          // store token in session by default (popup flow)
          import('@/services/auth').then(({ setToken }) => {
            setToken(event.data.token, false);
            router.push('/dashboard');
          });
        }
    };

    window.addEventListener('message', handleMessage);
    return () => {
      window.removeEventListener('message', handleMessage);
      if (slowRef.current) clearTimeout(slowRef.current);
    };
  }, [router]);

  const strength = password.length > 0 ? passStrength(password) : null;
  const passMismatch = mode === 'signup' && confirmPass.length > 0 && confirmPass !== password;
  const isValid = (() => {
    if (!email) return false;
    if (mode === 'login') return !!password;
    if (mode === 'forgot') return true;
    if (!fullName || !password || password !== confirmPass) return false;
    if (!passRules.every(r => r.test(password))) return false;
    return termsAccepted;
  })();

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError(''); setSuccess('');
    if (!isValid) return;

    if (mode === 'forgot') {
      setSuccess('If this email exists, a reset link has been sent. Check your inbox.');
      return;
    }

    setLoading(true);
    slowRef.current = setTimeout(() => setSlowHint(true), 5000);
    try {
      const res = mode === 'signup'
        ? await api.signup({ email, full_name: fullName, password })
        : await api.login({ email, password });

      // centralize token storage (remember => persistent)
      const { setToken } = await import('@/services/auth');
      setToken(res.access_token, rememberMe);
      router.push('/dashboard');
    } catch (err) {
      const msg = err instanceof TypeError && err.message === 'Failed to fetch'
        ? 'Server is waking up — please wait and try again.'
        : err instanceof Error ? err.message : 'Authentication failed';
      setError(msg);
    } finally {
      setLoading(false); setSlowHint(false);
      if (slowRef.current) clearTimeout(slowRef.current);
    }
  }

  const googleLogin = useGoogleLogin({
    onSuccess: async (tokenResponse) => {
      try {
        setLoading(true);
        const res = await api.googleLogin(tokenResponse.access_token);
        const { setToken } = await import('@/services/auth');
        setToken(res.access_token, true);
        router.push('/dashboard');
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Google login failed');
      } finally {
        setLoading(false);
      }
    },
    onError: () => setError('Google login failed'),
  });

  const handleGithubLogin = () => {
    const width = 600;
    const height = 700;
    const left = window.screenX + (window.outerWidth - width) / 2;
    const top = window.screenY + (window.outerHeight - height) / 2;
    
    const apiBase = process.env.NEXT_PUBLIC_API_BASE_URL || '';
    window.open(
      `${apiBase}/api/v1/auth/github/start`,
      'GitHub Login',
      `width=${width},height=${height},left=${left},top=${top},status=no,location=no`
    );
  };

  const featurePills = [
    { icon: Brain, label: 'Multi-Agent AI' },
    { icon: Mic, label: 'Live Coaching' },
    { icon: Zap, label: 'XP & Streaks' },
  ];

  return (
    <>
      {modal && <PolicyModal title={modal === 'terms' ? 'Terms & Conditions' : 'Privacy Policy'} onClose={() => setModal(null)} />}

      <main className="relative min-h-screen overflow-hidden" style={{ background: 'var(--bg-deep)' }}>
        {/* Background orbs */}
        <div className="pointer-events-none absolute inset-0">
          <div className="bg-orb bg-orb-cyan absolute -top-32 -left-32 h-96 w-96" />
          <div className="bg-orb bg-orb-violet absolute -bottom-32 -right-32 h-96 w-96" style={{ animationDelay: '3s' }} />
          <div className="bg-orb bg-orb-amber absolute top-1/2 left-1/2 h-64 w-64 -translate-x-1/2 -translate-y-1/2" style={{ animationDelay: '5s', opacity: 0.08 }} />
        </div>

        {/* Grid pattern overlay */}
        <div className="pointer-events-none absolute inset-0" style={{
          backgroundImage: 'linear-gradient(rgba(0,229,255,0.03) 1px,transparent 1px),linear-gradient(90deg,rgba(0,229,255,0.03) 1px,transparent 1px)',
          backgroundSize: '60px 60px',
        }} />

        <div className="relative z-10 flex min-h-screen flex-col items-center justify-center p-4 sm:p-8">
          {/* Logo */}
          <motion.div className="mb-8 flex items-center gap-3"
            initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
            <div className="flex h-11 w-11 items-center justify-center rounded-xl"
              style={{ background: 'linear-gradient(135deg,var(--accent-cyan),var(--accent-violet))', boxShadow: '0 0 30px rgba(0,229,255,0.3)' }}>
              <Mic className="h-5 w-5 text-white" />
            </div>
            <span className="text-2xl font-bold" style={{ fontFamily: 'Outfit,sans-serif', color: 'var(--ink)' }}>
              <span className="gradient-text">AI</span> Coach
            </span>
          </motion.div>

          {/* Feature pills */}
          <motion.div className="mb-8 flex flex-wrap justify-center gap-2"
            initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.2 }}>
            {featurePills.map(({ icon: Icon, label }) => (
              <span key={label} className="flex items-center gap-1.5 rounded-full px-3 py-1.5 text-xs font-medium"
                style={{ background: 'rgba(0,229,255,0.08)', border: '1px solid rgba(0,229,255,0.15)', color: 'var(--accent-cyan)' }}>
                <Icon className="h-3 w-3" />{label}
              </span>
            ))}
          </motion.div>

          {/* Card */}
          <motion.div className="glass w-full max-w-md rounded-3xl p-8"
            style={{ boxShadow: '0 25px 80px rgba(0,0,0,0.5), 0 0 60px rgba(0,229,255,0.04)' }}
            initial={{ opacity: 0, y: 30, scale: 0.97 }} animate={{ opacity: 1, y: 0, scale: 1 }}
            transition={{ duration: 0.5, delay: 0.1 }}>

            {/* Tabs */}
            {mode !== 'forgot' && (
              <div className="mb-8 flex rounded-xl p-1" role="tablist" style={{ background: 'rgba(0,0,0,0.3)', border: '1px solid var(--border)' }}>
                {(['login', 'signup'] as const).map(m => (
                  <button 
                    key={m} 
                    onClick={() => { setMode(m); setError(''); setSuccess(''); }}
                    className="relative flex-1 rounded-lg py-2.5 text-sm font-semibold transition-all duration-300"
                    style={{ color: mode === m ? '#fff' : 'var(--ink-muted)' }}
                    role="tab"
                    aria-selected={mode === m}
                    aria-controls={`panel-${m}`}
                  >
                    {mode === m && (
                      <motion.div layoutId="tab-bg" className="absolute inset-0 rounded-lg"
                        style={{ background: 'linear-gradient(135deg,var(--accent-cyan),var(--accent-violet))' }} />
                    )}
                    <span className="relative z-10 capitalize">{m === 'login' ? 'Sign In' : 'Sign Up'}</span>
                  </button>
                ))}
              </div>
            )}

            {/* Heading */}
            <div className="mb-6">
              <h1 className="text-2xl font-bold" style={{ color: 'var(--ink)' }}>
                {mode === 'login' ? 'Welcome back 👋' : mode === 'signup' ? 'Create your account ✨' : 'Reset Password 🔑'}
              </h1>
              <p className="mt-1 text-sm" style={{ color: 'var(--ink-muted)' }}>
                {mode === 'login' ? 'Sign in to continue your coaching journey.' : mode === 'signup' ? 'Join thousands training with AI.' : 'Enter your email and we\'ll send a reset link.'}
              </p>
            </div>

            <form onSubmit={onSubmit} className="space-y-4" aria-label={mode === 'login' ? 'Sign in form' : mode === 'signup' ? 'Sign up form' : 'Password reset form'}>
              {/* Full name */}
              {mode === 'signup' && (
                <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }} exit={{ opacity: 0, height: 0 }}>
                  <label htmlFor="auth-fullname" className="mb-1.5 block text-xs font-medium uppercase tracking-wider" style={{ color: 'var(--ink-muted)' }}>Full Name</label>
                  <div className="relative">
                    <User className="absolute left-3 top-3.5 h-4 w-4" style={{ color: 'var(--ink-muted)' }} aria-hidden="true" />
                    <input id="auth-fullname" required value={fullName} onChange={e => setFullName(e.target.value)}
                      placeholder="Jane Smith" className="input-dark pl-10" aria-required="true" />
                  </div>
                </motion.div>
              )}

              {/* Email */}
              <div>
                <label htmlFor="auth-email" className="mb-1.5 block text-xs font-medium uppercase tracking-wider" style={{ color: 'var(--ink-muted)' }}>Email Address</label>
                <div className="relative">
                  <Mail className="absolute left-3 top-3.5 h-4 w-4" style={{ color: 'var(--ink-muted)' }} aria-hidden="true" />
                  <input id="auth-email" type="email" required value={email} onChange={e => setEmail(e.target.value)}
                    placeholder="you@example.com" className="input-dark pl-10" aria-required="true" />
                </div>
              </div>

              {/* Password */}
              {mode !== 'forgot' && (
                <div>
                  <label htmlFor="auth-password" className="mb-1.5 block text-xs font-medium uppercase tracking-wider" style={{ color: 'var(--ink-muted)' }}>Password</label>
                  <div className="relative">
                    <Lock className="absolute left-3 top-3.5 h-4 w-4" style={{ color: 'var(--ink-muted)' }} aria-hidden="true" />
                    <input id="auth-password" type={showPass ? 'text' : 'password'} required value={password}
                      onChange={e => setPassword(e.target.value)} placeholder={mode === 'signup' ? 'Min 8 chars, strong password' : 'Enter your password'}
                      className="input-dark pl-10 pr-10" aria-required="true" aria-describedby={mode === 'signup' ? 'password-strength' : undefined} />
                    <button 
                      type="button" 
                      onClick={() => setShowPass(v => !v)}
                      className="absolute right-3 top-3.5 transition hover:opacity-70"
                      aria-label={showPass ? 'Hide password' : 'Show password'}
                      aria-pressed={showPass}
                    >
                      {showPass ? <EyeOff className="h-4 w-4" style={{ color: 'var(--ink-muted)' }} aria-hidden="true" /> : <Eye className="h-4 w-4" style={{ color: 'var(--ink-muted)' }} aria-hidden="true" />}
                    </button>
                  </div>

                  {/* Strength meter */}
                  {mode === 'signup' && password.length > 0 && strength && (
                    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="mt-2 space-y-2" id="password-strength" role="status" aria-live="polite">
                      <div className="flex items-center justify-between text-xs">
                        <span style={{ color: 'var(--ink-muted)' }}>Strength</span>
                        <span className="font-semibold" style={{ color: strength.color }}>{strength.label}</span>
                      </div>
                      <div className="h-1.5 overflow-hidden rounded-full" style={{ background: 'var(--border)' }} role="progressbar" aria-valuenow={strength.pct} aria-valuemin={0} aria-valuemax={100} aria-label="Password strength">
                        <motion.div className="h-full rounded-full" animate={{ width: `${strength.pct}%` }}
                          style={{ background: strength.color }} transition={{ duration: 0.4 }} />
                      </div>
                      <div className="grid grid-cols-2 gap-1">
                        {passRules.map(r => (
                          <div key={r.label} className="flex items-center gap-1.5 text-xs">
                            <div className={`h-3.5 w-3.5 rounded-full flex items-center justify-center transition-colors duration-300`}
                              style={{ background: r.test(password) ? 'rgba(16,185,129,0.2)' : 'rgba(100,116,139,0.15)', border: `1px solid ${r.test(password) ? '#10b981' : 'rgba(100,116,139,0.3)'}` }}
                              role="img" aria-label={r.test(password) ? `${r.label}: met` : `${r.label}: not met`}>
                              {r.test(password) && <Check className="h-2 w-2 text-emerald-400" aria-hidden="true" />}
                            </div>
                            <span style={{ color: r.test(password) ? 'var(--ink-secondary)' : 'var(--ink-muted)' }}>{r.label}</span>
                          </div>
                        ))}
                      </div>
                    </motion.div>
                  )}
                </div>
              )}

              {/* Confirm password */}
              {mode === 'signup' && (
                <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }}>
                  <label htmlFor="auth-confirm" className="mb-1.5 block text-xs font-medium uppercase tracking-wider" style={{ color: 'var(--ink-muted)' }}>Confirm Password</label>
                  <div className="relative">
                    <Lock className="absolute left-3 top-3.5 h-4 w-4" style={{ color: 'var(--ink-muted)' }} aria-hidden="true" />
                    <input id="auth-confirm" type={showConfirm ? 'text' : 'password'} value={confirmPass}
                      onChange={e => setConfirmPass(e.target.value)} placeholder="Re-enter password"
                      className="input-dark pl-10 pr-10" style={{ borderColor: passMismatch ? 'var(--accent-rose)' : undefined }} />
                    <button type="button" onClick={() => setShowConfirm(v => !v)} className="absolute right-3 top-3.5 transition hover:opacity-70">
                      {showConfirm ? <EyeOff className="h-4 w-4" style={{ color: 'var(--ink-muted)' }} /> : <Eye className="h-4 w-4" style={{ color: 'var(--ink-muted)' }} />}
                    </button>
                  </div>
                  {passMismatch && <p className="mt-1.5 text-xs" style={{ color: 'var(--accent-rose)' }}>Passwords do not match</p>}
                  {!passMismatch && confirmPass && confirmPass === password && (
                    <p className="mt-1.5 flex items-center gap-1 text-xs" style={{ color: '#10b981' }}><Check className="h-3 w-3" />Passwords match</p>
                  )}
                </motion.div>
              )}

              {/* Remember me / Forgot password */}
              {mode === 'login' && (
                <div className="flex items-center justify-between">
                  <label className="flex cursor-pointer items-center gap-2 text-sm">
                    <div onClick={() => setRememberMe(v => !v)}
                      className="flex h-4 w-4 items-center justify-center rounded transition-all duration-200 cursor-pointer"
                      style={{ background: rememberMe ? 'var(--accent-cyan)' : 'transparent', border: `1px solid ${rememberMe ? 'var(--accent-cyan)' : 'var(--border)'}` }}>
                      {rememberMe && <Check className="h-2.5 w-2.5 text-black" />}
                    </div>
                    <span style={{ color: 'var(--ink-secondary)' }}>Remember me</span>
                  </label>
                  <button type="button" onClick={() => { setMode('forgot'); setError(''); setSuccess(''); }}
                    className="text-sm font-medium transition hover:opacity-80" style={{ color: 'var(--accent-cyan)' }}>
                    Forgot password?
                  </button>
                </div>
              )}

              {/* Terms */}
              {mode === 'signup' && (
                <div className="flex items-start gap-3 rounded-xl p-3" style={{ background: 'rgba(0,229,255,0.04)', border: '1px solid rgba(0,229,255,0.1)' }}>
                  <div onClick={() => setTermsAccepted(v => !v)}
                    className="mt-0.5 flex h-4 w-4 flex-shrink-0 cursor-pointer items-center justify-center rounded transition-all duration-200"
                    style={{ background: termsAccepted ? 'var(--accent-cyan)' : 'transparent', border: `1px solid ${termsAccepted ? 'var(--accent-cyan)' : 'var(--border)'}` }}>
                    {termsAccepted && <Check className="h-2.5 w-2.5 text-black" />}
                  </div>
                  <p className="text-xs leading-relaxed" style={{ color: 'var(--ink-secondary)' }}>
                    I agree to the{' '}
                    <button type="button" onClick={() => setModal('terms')} className="font-semibold underline underline-offset-2 transition hover:opacity-80" style={{ color: 'var(--accent-cyan)' }}>Terms & Conditions</button>
                    {' '}and{' '}
                    <button type="button" onClick={() => setModal('privacy')} className="font-semibold underline underline-offset-2 transition hover:opacity-80" style={{ color: 'var(--accent-violet)' }}>Privacy Policy</button>
                  </p>
                </div>
              )}

              {/* Error / Success */}
              <AnimatePresence>
                {error && (
                  <motion.div initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}
                    className="flex items-start gap-2 rounded-xl p-3 text-sm"
                    style={{ background: 'rgba(244,63,94,0.1)', border: '1px solid rgba(244,63,94,0.2)', color: 'var(--accent-rose)' }}>
                    <X className="mt-0.5 h-4 w-4 flex-shrink-0" />{error}
                  </motion.div>
                )}
                {success && (
                  <motion.div initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}
                    className="flex items-start gap-2 rounded-xl p-3 text-sm"
                    style={{ background: 'rgba(16,185,129,0.1)', border: '1px solid rgba(16,185,129,0.2)', color: '#10b981' }}>
                    <Check className="mt-0.5 h-4 w-4 flex-shrink-0" />{success}
                  </motion.div>
                )}
              </AnimatePresence>

              {/* Submit */}
              <motion.button id="auth-submit" type="submit" disabled={loading || !isValid}
                className="btn-primary w-full flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
                whileHover={{ scale: 1.01 }} whileTap={{ scale: 0.98 }}>
                {loading ? (
                  <><Loader2 className="h-4 w-4 animate-spin" /><span>{slowHint ? 'Server waking up...' : 'Please wait...'}</span></>
                ) : (
                  <><Sparkles className="h-4 w-4" />{mode === 'login' ? 'Sign In' : mode === 'signup' ? 'Create Account' : 'Send Reset Link'}<ArrowRight className="h-4 w-4" /></>
                )}
              </motion.button>

              {mode === 'forgot' && (
                <button type="button" onClick={() => { setMode('login'); setSuccess(''); setError(''); }}
                  className="w-full text-center text-sm transition hover:opacity-80" style={{ color: 'var(--ink-muted)' }}>
                  ← Back to Sign In
                </button>
              )}
            </form>

            {/* Divider + Google */}
            {mode !== 'forgot' && (
              <>
                <div className="relative my-6 flex items-center">
                  <div className="flex-1" style={{ borderTop: '1px solid var(--border)' }} />
                  <span className="mx-3 text-xs uppercase tracking-wider" style={{ color: 'var(--ink-muted)' }}>or continue with</span>
                  <div className="flex-1" style={{ borderTop: '1px solid var(--border)' }} />
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <motion.button
                    type="button"
                    onClick={() => googleLogin()}
                    className="flex items-center justify-center gap-2 rounded-xl border py-2.5 text-sm font-semibold transition-all hover:bg-white/5"
                    style={{ borderColor: 'var(--border)', color: 'var(--ink)' }}
                    whileHover={{ y: -2, boxShadow: '0 4px 12px rgba(0,0,0,0.2)' }}
                    whileTap={{ scale: 0.98 }}
                  >
                    <svg className="h-4 w-4" viewBox="0 0 24 24">
                      <path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" />
                      <path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" />
                      <path fill="#FBBC05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l3.66-2.84z" />
                      <path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" />
                    </svg>
                    Google
                  </motion.button>
                  <motion.button
                    type="button"
                    onClick={handleGithubLogin}
                    className="flex items-center justify-center gap-2 rounded-xl border py-2.5 text-sm font-semibold transition-all hover:bg-white/5"
                    style={{ borderColor: 'var(--border)', color: 'var(--ink)' }}
                    whileHover={{ y: -2, boxShadow: '0 4px 12px rgba(0,0,0,0.2)' }}
                    whileTap={{ scale: 0.98 }}
                  >
                    <Github className="h-4 w-4" />
                    GitHub
                  </motion.button>
                </div>
              </>
            )}
          </motion.div>

          {/* Footer */}
          <motion.p className="mt-8 text-center text-xs" style={{ color: 'var(--ink-muted)' }}
            initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.6 }}>
            Protected by enterprise-grade encryption. Your data stays private.
          </motion.p>
        </div>
      </main>
    </>
  );
}
