'use client';

import { useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { motion, AnimatePresence } from 'framer-motion';
import dynamic from 'next/dynamic';
import {
  ArrowRight, Brain, Check, Eye, EyeOff, Github, Loader2,
  Lock, Mail, Mic, Shield, Sparkles, User, X, Zap,
  Video, Users, Trophy, Cpu, Fingerprint, Scan
} from 'lucide-react';
import { useGoogleLogin } from '@react-oauth/google';
import { api } from '@/services/api';

const ThreeScene = dynamic(() => import('@/components/ThreeScene').then(mod => mod.ThreeScene), { ssr: false });

/* ── helpers ── */
const passRules = [
  { label: 'At least 8 characters', test: (p: string) => p.length >= 8 },
  { label: 'Uppercase letter', test: (p: string) => /[A-Z]/.test(p) },
  { label: 'Lowercase letter', test: (p: string) => /[a-z]/.test(p) },
  { label: 'Number', test: (p: string) => /\d/.test(p) },
  { label: 'Special character', test: (p: string) => /[^A-Za-z0-9]/.test(p) },
];

function passStrength(p: string) {
  const score = passRules.filter(r => r.test(p)).length;
  if (score <= 1) return { label: 'Very Weak', color: '#f43f5e', pct: 20 };
  if (score === 2) return { label: 'Weak', color: '#f59e0b', pct: 40 };
  if (score === 3) return { label: 'Fair', color: '#eab308', pct: 60 };
  if (score === 4) return { label: 'Strong', color: '#10b981', pct: 80 };
  return { label: 'Very Strong', color: '#00e5ff', pct: 100 };
}

/* ── Feature Card for Left Panel ── */
function FeatureCard({ icon: Icon, title, description, delay }: { icon: any, title: string, description: string, delay: number }) {
  return (
    <motion.div
      initial={{ opacity: 0, x: -30 }}
      animate={{ opacity: 1, x: 0 }}
      transition={{ delay, duration: 0.5 }}
      className="group flex items-start gap-4 p-4 rounded-xl bg-white/5 border border-white/10 hover:border-cyan-500/30 transition-all duration-300 cursor-default"
    >
      <div className="relative">
        <div className="absolute inset-0 bg-cyan-500/20 blur-xl rounded-full group-hover:bg-cyan-500/30 transition-all" />
        <div className="relative p-3 rounded-lg bg-gradient-to-br from-cyan-500/20 to-violet-500/20 border border-white/10">
          <Icon className="w-5 h-5 text-cyan-400" />
        </div>
      </div>
      <div>
        <h3 className="text-white font-semibold text-sm mb-1">{title}</h3>
        <p className="text-white/50 text-xs leading-relaxed">{description}</p>
      </div>
    </motion.div>
  );
}

/* ── Modal ── */
function PolicyModal({ title, onClose }: { title: string; onClose: () => void }) {
  return (
    <AnimatePresence>
      <motion.div
        className="fixed inset-0 z-50 flex items-center justify-center p-4"
        initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
      >
        <div className="absolute inset-0 bg-black/80 backdrop-blur-xl" onClick={onClose} />
        <motion.div
          className="relative z-10 w-full max-w-lg glass-ultra border border-white/10"
          initial={{ scale: 0.9, opacity: 0 }} animate={{ scale: 1, opacity: 1 }}
        >
          <div className="flex items-center justify-between mb-6 p-6 pb-0">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-gradient-to-br from-cyan-500/20 to-violet-500/20 border border-white/10">
                <Shield className="h-5 w-5 text-cyan-400" />
              </div>
              <h2 className="text-xl font-bold text-white">{title}</h2>
            </div>
            <button onClick={onClose} className="p-2 rounded-lg hover:bg-white/10 transition">
              <X className="h-5 w-5 text-white/50" />
            </button>
          </div>
          <div className="p-6 pt-0 space-y-4 text-sm text-white/60 max-h-[60vh] overflow-y-auto">
            {title === 'Terms & Conditions' ? (
              <>
                <p><strong className="text-white">1. Acceptance of Terms</strong><br />By accessing AI Communication Coach, you agree to these Terms & Conditions.</p>
                <p><strong className="text-white">2. Use of Service</strong><br />You may use this platform for personal communication skill development.</p>
                <p><strong className="text-white">3. AI-Generated Content</strong><br />Feedback and scores are generated by AI models for advisory purposes.</p>
                <p><strong className="text-white">4. Account Responsibility</strong><br />You are responsible for maintaining your account credentials.</p>
              </>
            ) : (
              <>
                <p><strong className="text-white">1. Data We Collect</strong><br />We collect your email, name, and session transcripts to improve our service.</p>
                <p><strong className="text-white">2. How We Use Your Data</strong><br />Your data is used exclusively to power AI coaching features.</p>
                <p><strong className="text-white">3. Data Storage</strong><br />Data is stored securely using industry-standard encryption.</p>
              </>
            )}
          </div>
          <div className="p-6 pt-0">
            <button onClick={onClose} className="btn-primary w-full">Got it</button>
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}

/* ── Main Auth Page ── */
export default function AuthPage() {
  const router = useRouter();
  const [mode, setMode] = useState<'login' | 'signup' | 'forgot'>('login');
  const [email, setEmail] = useState('');
  const [fullName, setFullName] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPass, setConfirmPass] = useState('');
  const [showPass, setShowPass] = useState(false);
  const [showConfirm, setShowConfirm] = useState(false);
  const [rememberMe, setRememberMe] = useState(false);
  const [termsAccepted, setTermsAccepted] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [slowHint, setSlowHint] = useState(false);
  const [modal, setModal] = useState<'terms' | 'privacy' | null>(null);
  const [particles, setParticles] = useState<Array<{id: number, x: number, y: number}>>([]);
  const slowRef = useRef<NodeJS.Timeout | null>(null);

  // Generate particles
  useEffect(() => {
    const newParticles = Array.from({ length: 15 }, (_, i) => ({
      id: i,
      x: Math.random() * 100,
      y: Math.random() * 100,
    }));
    setParticles(newParticles);
  }, []);

  useEffect(() => {
    const handleMessage = (event: MessageEvent) => {
      if (event.origin !== window.location.origin && event.origin !== 'http://localhost:8000') {
        if (!event.origin.includes('localhost') && !event.origin.includes('render.com')) return;
      }
      if (event.data?.type === 'oauth-token' && event.data?.token) {
        import('@/services/auth').then(({ setToken }) => {
          setToken(event.data.token, false);
          router.push('/dashboard');
        });
      }
    };
    window.addEventListener('message', handleMessage);
    return () => {
      window.removeEventListener('message', handleMessage);
      if (slowRef.current) clearTimeout(slowRef.current);
    };
  }, [router]);

  const strength = password.length > 0 ? passStrength(password) : null;
  const passMismatch = mode === 'signup' && confirmPass.length > 0 && confirmPass !== password;
  const isValid = (() => {
    if (!email) return false;
    if (mode === 'login') return !!password;
    if (mode === 'forgot') return true;
    if (!fullName || !password || password !== confirmPass) return false;
    if (!passRules.every(r => r.test(password))) return false;
    return termsAccepted;
  })();

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError(''); setSuccess('');
    if (!isValid) return;

    if (mode === 'forgot') {
      setLoading(true);
      try {
        const res = await api.forgotPassword(email);
        setSuccess(res.message);
      } catch (err) {
        const msg = err instanceof Error ? err.message : 'Failed to send reset link';
        setError(msg);
      } finally {
        setLoading(false);
      }
      return;
    }

    setLoading(true);
    slowRef.current = setTimeout(() => setSlowHint(true), 5000);
    try {
      const res = mode === 'signup'
        ? await api.signup({ email, full_name: fullName, password })
        : await api.login({ email, password });
      const { setToken } = await import('@/services/auth');
      setToken(res.access_token, rememberMe);
      router.push('/dashboard');
    } catch (err) {
      const msg = err instanceof TypeError && err.message === 'Failed to fetch'
        ? 'Server is waking up — please wait and try again.'
        : err instanceof Error ? err.message : 'Authentication failed';
      setError(msg);
    } finally {
      setLoading(false); setSlowHint(false);
      if (slowRef.current) clearTimeout(slowRef.current);
    }
  }

  const googleLogin = useGoogleLogin({
    onSuccess: async (tokenResponse) => {
      try {
        setLoading(true);
        const res = await api.googleLogin(tokenResponse.access_token);
        const { setToken } = await import('@/services/auth');
        setToken(res.access_token, true);
        router.push('/dashboard');
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Google login failed');
      } finally {
        setLoading(false);
      }
    },
    onError: () => setError('Google login failed'),
  });

  const handleGithubLogin = () => {
    const width = 600, height = 700;
    const left = window.screenX + (window.outerWidth - width) / 2;
    const top = window.screenY + (window.outerHeight - height) / 2;
    const apiBase = process.env.NEXT_PUBLIC_API_BASE_URL || '';
    window.open(
      `${apiBase}/api/v1/auth/github/start`,
      'GitHub Login',
      `width=${width},height=${height},left=${left},top=${top},status=no,location=no`
    );
  };

  const features = [
    { icon: Brain, title: 'Multi-Agent AI', description: '5 specialized AI agents analyze your communication patterns in real-time' },
    { icon: Mic, title: 'Voice Analysis', description: 'Advanced speech pattern recognition for pitch, pace, and clarity scoring' },
    { icon: Video, title: 'Face Recognition', description: 'MediaPipe-powered face tracking for confidence and engagement metrics' },
    { icon: Users, title: 'Team Sessions', description: 'Collaborative practice rooms with WebRTC video conferencing' },
    { icon: Trophy, title: 'Gamified Learning', description: 'XP, streaks, achievements, and global leaderboards' },
    { icon: Scan, title: 'Real-time Feedback', description: 'Instant AI coaching tips as you practice' },
  ];

  return (
    <>
      {modal && <PolicyModal title={modal === 'terms' ? 'Terms & Conditions' : 'Privacy Policy'} onClose={() => setModal(null)} />}

      <main className="relative min-h-screen flex overflow-hidden bg-[#050810]">
        {/* Left Panel - 3D Scene + Features */}
        <div className="hidden lg:flex lg:w-1/2 relative flex-col">
          {/* 3D Background */}
          <div className="absolute inset-0 z-0">
            <ThreeScene variant="geometric" interactive={false} />
          </div>

          {/* Animated Gradient Orbs */}
          <div className="absolute inset-0 z-[1] pointer-events-none">
            <motion.div
              className="absolute left-1/4 top-1/4 h-[500px] w-[500px] rounded-full bg-gradient-to-r from-cyan-500/20 to-blue-500/10 blur-[120px]"
              animate={{ x: [0, 30, 0], y: [0, -20, 0], scale: [1, 1.1, 1] }}
              transition={{ duration: 8, repeat: Infinity, ease: "easeInOut" }}
            />
            <motion.div
              className="absolute bottom-1/3 right-1/4 h-[400px] w-[400px] rounded-full bg-gradient-to-r from-violet-500/20 to-purple-500/10 blur-[100px]"
              animate={{ x: [0, -20, 0], y: [0, 30, 0], scale: [1, 1.15, 1] }}
              transition={{ duration: 10, repeat: Infinity, ease: "easeInOut", delay: 2 }}
            />
          </div>

          {/* Floating Particles */}
          <div className="absolute inset-0 z-[2] pointer-events-none overflow-hidden">
            {particles.map((particle) => (
              <motion.div
                key={particle.id}
                className="absolute w-1 h-1 rounded-full bg-cyan-400/20"
                style={{ left: `${particle.x}%`, top: `${particle.y}%` }}
                animate={{ y: [-15, 15, -15], opacity: [0.2, 0.5, 0.2] }}
                transition={{ duration: 5 + Math.random() * 3, repeat: Infinity, ease: "easeInOut", delay: Math.random() * 2 }}
              />
            ))}
          </div>

          {/* Content */}
          <div className="relative z-10 flex flex-col h-full p-12">
            {/* Logo */}
            <motion.div
              className="flex items-center gap-3 mb-12"
              initial={{ opacity: 0, y: -20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
            >
              <div className="relative">
                <motion.div
                  className="absolute inset-0 bg-cyan-500/30 blur-xl rounded-lg"
                  animate={{ scale: [1, 1.2, 1], opacity: [0.5, 0.8, 0.5] }}
                  transition={{ duration: 2, repeat: Infinity }}
                />
                <div className="relative p-3 rounded-xl bg-gradient-to-br from-cyan-500 to-violet-600">
                  <Zap className="h-6 w-6 text-white" />
                </div>
              </div>
              <div>
                <span className="text-2xl font-bold bg-gradient-to-r from-white to-white/70 bg-clip-text text-transparent">
                  AI Coach
                </span>
                <p className="text-xs text-cyan-400/80 tracking-widest uppercase">Next-Gen Communication Training</p>
              </div>
            </motion.div>

            {/* Features Grid */}
            <div className="flex-1 flex flex-col justify-center">
              <motion.h2
                className="text-3xl font-bold text-white mb-2"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.3 }}
              >
                Master Your Communication
              </motion.h2>
              <motion.p
                className="text-white/50 mb-8 text-sm"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.4 }}
              >
                Join 10,000+ professionals training with AI-powered feedback
              </motion.p>

              <div className="grid gap-3 max-w-md">
                {features.map((feature, index) => (
                  <FeatureCard key={feature.title} {...feature} delay={0.5 + index * 0.1} />
                ))}
              </div>
            </div>

            {/* Bottom Stats */}
            <motion.div
              className="flex gap-8 mt-auto"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 1.2 }}
            >
              <div>
                <p className="text-2xl font-bold text-white">50K+</p>
                <p className="text-xs text-white/50">Active Users</p>
              </div>
              <div>
                <p className="text-2xl font-bold text-white">1M+</p>
                <p className="text-xs text-white/50">Sessions Completed</p>
              </div>
              <div>
                <p className="text-2xl font-bold text-white">4.9</p>
                <p className="text-xs text-white/50">User Rating</p>
              </div>
            </motion.div>
          </div>

          {/* Corner Accents */}
          <div className="absolute inset-0 z-[5] pointer-events-none">
            <div className="hud-corner hud-corner-tl" />
            <div className="hud-corner hud-corner-bl" />
          </div>
        </div>

        {/* Right Panel - Auth Form */}
        <div className="flex-1 relative flex flex-col items-center justify-center p-6 lg:p-12">
          {/* Background Effects */}
          <div className="absolute inset-0 z-0 opacity-50">
            <div className="absolute top-1/4 right-1/4 h-[300px] w-[300px] rounded-full bg-violet-500/10 blur-[100px]" />
            <div className="absolute bottom-1/4 left-1/4 h-[250px] w-[250px] rounded-full bg-cyan-500/10 blur-[80px]" />
          </div>

          {/* Grid Pattern */}
          <div className="absolute inset-0 z-[1] opacity-10 grid-bg" />

          {/* Mobile Logo */}
          <motion.div
            className="lg:hidden flex items-center gap-3 mb-8"
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
          >
            <div className="p-2 rounded-lg bg-gradient-to-br from-cyan-500 to-violet-600">
              <Zap className="h-5 w-5 text-white" />
            </div>
            <span className="text-xl font-bold text-white">AI Coach</span>
          </motion.div>

          {/* Auth Card */}
          <motion.div
            className="relative z-10 w-full max-w-md"
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
          >
            <div className="glass-ultra rounded-3xl p-8 border border-white/10">
              {/* Corner Accents */}
              <div className="corner-accent absolute inset-0 rounded-3xl pointer-events-none" />

              {/* Tabs */}
              {mode !== 'forgot' && (
                <div className="mb-8 flex rounded-xl p-1 bg-black/30 border border-white/10">
                  {(['login', 'signup'] as const).map((m) => (
                    <button
                      key={m}
                      onClick={() => { setMode(m); setError(''); setSuccess(''); }}
                      className="relative flex-1 rounded-lg py-2.5 text-sm font-semibold transition-all duration-300"
                      style={{ color: mode === m ? '#fff' : 'rgba(255,255,255,0.5)' }}
                    >
                      {mode === m && (
                        <motion.div
                          layoutId="tab-bg"
                          className="absolute inset-0 rounded-lg bg-gradient-to-r from-cyan-500 to-violet-600"
                          transition={{ type: "spring", stiffness: 500, damping: 30 }}
                        />
                      )}
                      <span className="relative z-10">{m === 'login' ? 'Sign In' : 'Sign Up'}</span>
                    </button>
                  ))}
                </div>
              )}

              {/* Heading */}
              <div className="mb-6 text-center">
                <motion.h1
                  className="text-2xl font-bold text-white"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ delay: 0.3 }}
                >
                  {mode === 'login' ? 'Welcome Back' : mode === 'signup' ? 'Create Account' : 'Reset Password'}
                </motion.h1>
                <motion.p
                  className="mt-1 text-sm text-white/50"
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ delay: 0.4 }}
                >
                  {mode === 'login' ? 'Continue your communication journey' : mode === 'signup' ? 'Start your AI-powered training' : 'Enter your email for reset link'}
                </motion.p>
              </div>

              {/* Form */}
              <form onSubmit={onSubmit} className="space-y-4">
                {/* Full Name */}
                {mode === 'signup' && (
                  <motion.div
                    initial={{ opacity: 0, height: 0 }}
                    animate={{ opacity: 1, height: 'auto' }}
                    className="space-y-1"
                  >
                    <label className="text-xs font-medium uppercase tracking-wider text-white/50">Full Name</label>
                    <div className="relative">
                      <User className="absolute left-3 top-3.5 h-4 w-4 text-white/30" />
                      <input
                        type="text"
                        required
                        name="fullName"
                        value={fullName}
                        onChange={(e) => setFullName(e.target.value)}
                        placeholder="John Doe"
                        className="w-full rounded-xl bg-white/5 border border-white/10 px-4 py-3 pl-10 text-white placeholder:text-white/30 focus:border-cyan-500/50 focus:ring-1 focus:ring-cyan-500/50 transition-all outline-none"
                      />
                    </div>
                  </motion.div>
                )}

                {/* Email */}
                <div className="space-y-1">
                  <label className="text-xs font-medium uppercase tracking-wider text-white/50">Email Address</label>
                  <div className="relative">
                    <Mail className="absolute left-3 top-3.5 h-4 w-4 text-white/30" />
                    <input
                      type="email"
                      required
                      name="email"
                      value={email}
                      onChange={(e) => setEmail(e.target.value)}
                      placeholder="you@example.com"
                      className="w-full rounded-xl bg-white/5 border border-white/10 px-4 py-3 pl-10 text-white placeholder:text-white/30 focus:border-cyan-500/50 focus:ring-1 focus:ring-cyan-500/50 transition-all outline-none"
                    />
                  </div>
                </div>

                {/* Password */}
                {mode !== 'forgot' && (
                  <div className="space-y-1">
                    <label className="text-xs font-medium uppercase tracking-wider text-white/50">Password</label>
                    <div className="relative">
                      <Lock className="absolute left-3 top-3.5 h-4 w-4 text-white/30" />
                      <input
                        type={showPass ? 'text' : 'password'}
                        required
                        name="password"
                        value={password}
                        onChange={(e) => setPassword(e.target.value)}
                        placeholder={mode === 'signup' ? 'Create a strong password' : 'Enter your password'}
                        className="w-full rounded-xl bg-white/5 border border-white/10 px-4 py-3 pl-10 pr-10 text-white placeholder:text-white/30 focus:border-cyan-500/50 focus:ring-1 focus:ring-cyan-500/50 transition-all outline-none"
                      />
                      <button
                        type="button"
                        onClick={() => setShowPass(!showPass)}
                        className="absolute right-3 top-3.5 text-white/30 hover:text-white/50 transition"
                      >
                        {showPass ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                      </button>
                    </div>

                    {/* Password Strength */}
                    {mode === 'signup' && password.length > 0 && strength && (
                      <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        className="mt-2 space-y-2"
                      >
                        <div className="flex items-center justify-between text-xs">
                          <span className="text-white/50">Strength</span>
                          <span className="font-semibold" style={{ color: strength.color }}>{strength.label}</span>
                        </div>
                        <div className="h-1.5 overflow-hidden rounded-full bg-white/10">
                          <motion.div
                            className="h-full rounded-full"
                            initial={{ width: 0 }}
                            animate={{ width: `${strength.pct}%` }}
                            style={{ background: strength.color }}
                            transition={{ duration: 0.3 }}
                          />
                        </div>
                        <div className="grid grid-cols-2 gap-1">
                          {passRules.map((r) => (
                            <div key={r.label} className="flex items-center gap-1.5 text-xs">
                              <div
                                className="h-3.5 w-3.5 rounded-full flex items-center justify-center transition-colors"
                                style={{
                                  background: r.test(password) ? 'rgba(16,185,129,0.2)' : 'rgba(255,255,255,0.05)',
                                  border: `1px solid ${r.test(password) ? '#10b981' : 'rgba(255,255,255,0.1)'}`
                                }}
                              >
                                {r.test(password) && <Check className="h-2 w-2 text-emerald-400" />}
                              </div>
                              <span className={r.test(password) ? 'text-white/70' : 'text-white/40'}>{r.label}</span>
                            </div>
                          ))}
                        </div>
                      </motion.div>
                    )}
                  </div>
                )}

                {/* Confirm Password */}
                {mode === 'signup' && (
                  <motion.div
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    className="space-y-1"
                  >
                    <label className="text-xs font-medium uppercase tracking-wider text-white/50">Confirm Password</label>
                    <div className="relative">
                      <Lock className="absolute left-3 top-3.5 h-4 w-4 text-white/30" />
                      <input
                        type={showConfirm ? 'text' : 'password'}
                        value={confirmPass}
                        onChange={(e) => setConfirmPass(e.target.value)}
                        placeholder="Confirm your password"
                        className={`w-full rounded-xl bg-white/5 border px-4 py-3 pl-10 pr-10 text-white placeholder:text-white/30 focus:border-cyan-500/50 focus:ring-1 focus:ring-cyan-500/50 transition-all outline-none ${
                          passMismatch ? 'border-red-500/50' : 'border-white/10'
                        }`}
                      />
                      <button
                        type="button"
                        onClick={() => setShowConfirm(!showConfirm)}
                        className="absolute right-3 top-3.5 text-white/30 hover:text-white/50 transition"
                      >
                        {showConfirm ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                      </button>
                    </div>
                    {passMismatch && (
                      <p className="text-xs text-red-400">Passwords do not match</p>
                    )}
                  </motion.div>
                )}

                {/* Remember Me / Forgot Password */}
                {mode === 'login' && (
                  <div className="flex items-center justify-between">
                    <label className="flex items-center gap-2 text-sm text-white/60 cursor-pointer">
                      <div
                        onClick={() => setRememberMe(!rememberMe)}
                        className={`flex h-4 w-4 items-center justify-center rounded transition-all cursor-pointer ${
                          rememberMe ? 'bg-cyan-500' : 'bg-white/10 border border-white/20'
                        }`}
                      >
                        {rememberMe && <Check className="h-3 w-3 text-black" />}
                      </div>
                      Remember me
                    </label>
                    <button
                      type="button"
                      onClick={() => { setMode('forgot'); setError(''); setSuccess(''); }}
                      className="text-sm text-cyan-400 hover:text-cyan-300 transition"
                    >
                      Forgot password?
                    </button>
                  </div>
                )}

                {/* Terms */}
                {mode === 'signup' && (
                  <div className="flex items-start gap-3 p-3 rounded-xl bg-cyan-500/5 border border-cyan-500/10">
                    <div
                      onClick={() => setTermsAccepted(!termsAccepted)}
                      className={`mt-0.5 flex h-4 w-4 flex-shrink-0 cursor-pointer items-center justify-center rounded transition-all ${
                        termsAccepted ? 'bg-cyan-500' : 'bg-white/10 border border-white/20'
                      }`}
                    >
                      {termsAccepted && <Check className="h-3 w-3 text-black" />}
                    </div>
                    <p className="text-xs text-white/60 leading-relaxed">
                      I agree to the{' '}
                      <button type="button" onClick={() => setModal('terms')} className="text-cyan-400 hover:text-cyan-300 underline">Terms</button>
                      {' '}and{' '}
                      <button type="button" onClick={() => setModal('privacy')} className="text-violet-400 hover:text-violet-300 underline">Privacy Policy</button>
                    </p>
                  </div>
                )}

                {/* Error / Success */}
                <AnimatePresence>
                  {error && (
                    <motion.div
                      initial={{ opacity: 0, y: -8 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0 }}
                      className="flex items-start gap-2 rounded-xl p-3 text-sm bg-red-500/10 border border-red-500/20 text-red-400"
                    >
                      <X className="mt-0.5 h-4 w-4 flex-shrink-0" />
                      {error}
                    </motion.div>
                  )}
                  {success && (
                    <motion.div
                      initial={{ opacity: 0, y: -8 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0 }}
                      className="flex items-start gap-2 rounded-xl p-3 text-sm bg-emerald-500/10 border border-emerald-500/20 text-emerald-400"
                    >
                      <Check className="mt-0.5 h-4 w-4 flex-shrink-0" />
                      {success}
                    </motion.div>
                  )}
                </AnimatePresence>

                {/* Submit Button */}
                <motion.button
                  type="submit"
                  disabled={loading || !isValid}
                  className="relative w-full overflow-hidden rounded-xl bg-gradient-to-r from-cyan-500 to-violet-600 py-3.5 font-semibold text-white disabled:opacity-50 disabled:cursor-not-allowed group"
                  whileHover={{ scale: 1.02 }}
                  whileTap={{ scale: 0.98 }}
                >
                  <div className="absolute inset-0 bg-white/20 translate-y-full group-hover:translate-y-0 transition-transform" />
                  <div className="relative flex items-center justify-center gap-2">
                    {loading ? (
                      <>
                        <Loader2 className="h-4 w-4 animate-spin" />
                        <span>{slowHint ? 'Connecting...' : 'Please wait...'}</span>
                      </>
                    ) : (
                      <>
                        <Sparkles className="h-4 w-4" />
                        <span>{mode === 'login' ? 'Sign In' : mode === 'signup' ? 'Create Account' : 'Send Reset Link'}</span>
                        <ArrowRight className="h-4 w-4" />
                      </>
                    )}
                  </div>
                </motion.button>

                {mode === 'forgot' && (
                  <button
                    type="button"
                    onClick={() => { setMode('login'); setSuccess(''); setError(''); }}
                    className="w-full text-center text-sm text-white/50 hover:text-white/70 transition"
                  >
                    ← Back to Sign In
                  </button>
                )}
              </form>

              {/* Divider */}
              {mode !== 'forgot' && (
                <div className="relative my-6">
                  <div className="absolute inset-0 flex items-center">
                    <div className="w-full border-t border-white/10" />
                  </div>
                  <div className="relative flex justify-center">
                    <span className="px-3 text-xs text-white/40 bg-[#0a0f1e] uppercase tracking-wider">
                      Or continue with
                    </span>
                  </div>
                </div>
              )}

              {/* OAuth Buttons */}
              {mode !== 'forgot' && (
                <div className="grid grid-cols-2 gap-3">
                  <motion.button
                    type="button"
                    onClick={() => googleLogin()}
                    className="flex items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/5 py-2.5 text-sm font-medium text-white/80 hover:bg-white/10 hover:border-white/20 transition-all"
                    whileHover={{ y: -2 }}
                    whileTap={{ scale: 0.98 }}
                  >
                    <svg className="h-4 w-4" viewBox="0 0 24 24">
                      <path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" />
                      <path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" />
                      <path fill="#FBBC05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l3.66-2.84z" />
                      <path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" />
                    </svg>
                    Google
                  </motion.button>
                  <motion.button
                    type="button"
                    onClick={handleGithubLogin}
                    className="flex items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/5 py-2.5 text-sm font-medium text-white/80 hover:bg-white/10 hover:border-white/20 transition-all"
                    whileHover={{ y: -2 }}
                    whileTap={{ scale: 0.98 }}
                  >
                    <Github className="h-4 w-4" />
                    GitHub
                  </motion.button>
                </div>
              )}
            </div>

            {/* Footer */}
            <motion.p
              className="mt-6 text-center text-xs text-white/40"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.8 }}
            >
              Protected by enterprise-grade encryption • TLS 1.3
            </motion.p>
          </motion.div>

          {/* Corner Accents */}
          <div className="absolute inset-0 z-[5] pointer-events-none lg:hidden">
            <div className="hud-corner hud-corner-tl" />
            <div className="hud-corner hud-corner-tr" />
            <div className="hud-corner hud-corner-bl" />
            <div className="hud-corner hud-corner-br" />
          </div>
        </div>
      </main>
    </>
  );
}
